// Spec A §3.1 step 3: Zod-validate the body after stripping any
// client-supplied tenant (decision 4 — the tenant comes from the JWT only).
import { z } from "./deps.ts";
import { GatewayError } from "./errors.ts";

const TENANT_KEYS = new Set(["tenantId", "tenant_id", "p_tenant_id"]);

export function stripTenantKeys(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(stripTenantKeys);
  if (value !== null && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value).filter(([k]) => !TENANT_KEYS.has(k)).map(([k, v]) => [k, stripTenantKeys(v)]),
    );
  }
  return value;
}

export async function parseJsonBody<S extends z.ZodTypeAny>(req: Request, schema: S): Promise<z.infer<S>> {
  let raw: unknown;
  try {
    raw = await req.json();
  } catch {
    throw new GatewayError(400, "INVALID_JSON", "Request body must be JSON.");
  }
  const result = schema.safeParse(stripTenantKeys(raw));
  if (!result.success) {
    throw new GatewayError(400, "VALIDATION_FAILED", "Request body is invalid.", result.error.flatten());
  }
  return result.data;
}

// generated by the client at enqueue time, not send time (§7.2)
export const idempotencyKey = z.string().uuid();
