-- Spec A §6.8 — platform plumbing (class D): tenant_id is nullable because
-- platform-level rows have no tenant.

-- ── otp_challenges ──────────────────────────────────────────────────────
-- §6.11: the shop-owner half of the dual-validation handshake. Hashed code,
-- single use, short expiry, attempt lockout, per-subject rate limiting.
create table public.otp_challenges (
  id                 uuid primary key default gen_random_uuid(),
  tenant_id          uuid references public.tenants (id) on delete restrict,
  subject_id         uuid not null references public.profiles (id) on delete restrict,
  purpose            public.otp_purpose_enum not null,
  code_hash          text not null,
  destination_phone  text not null check (destination_phone ~ '^\+[1-9][0-9]{7,14}$'),
  issued_by          uuid not null references public.profiles (id) on delete restrict,
  expires_at         timestamptz not null,
  consumed_at        timestamptz,
  failed_attempts    integer not null default 0 check (failed_attempts >= 0),
  locked_until       timestamptz,
  created_at         timestamptz not null default now(),
  constraint otp_challenges_expiry_after_issue check (expires_at > created_at)
);
alter table public.otp_challenges enable row level security;
-- issuance rate limiting looks back over a subject's recent challenges
create index idx_otp_challenges_subject on public.otp_challenges (subject_id, purpose, created_at desc);
create index idx_otp_challenges_issued_by on public.otp_challenges (issued_by);
create index idx_otp_challenges_tenant on public.otp_challenges (tenant_id);

-- ── idempotency_logs ────────────────────────────────────────────────────
-- §7.2: key is generated by the client at enqueue time. request_hash detects
-- a key reused with a different payload (§3.5 → 409). actor_id is null for
-- system-initiated work (webhooks, cron).
create table public.idempotency_logs (
  key           uuid primary key,
  tenant_id     uuid references public.tenants (id) on delete restrict,
  actor_id      uuid references public.profiles (id) on delete restrict,
  operation     text not null,
  request_hash  text not null,
  response      jsonb,
  status        text not null default 'IN_PROGRESS'
                  check (status in ('IN_PROGRESS', 'COMPLETED', 'FAILED')),
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
alter table public.idempotency_logs enable row level security;
create index idx_idempotency_logs_actor on public.idempotency_logs (actor_id, created_at desc);
create index idx_idempotency_logs_tenant on public.idempotency_logs (tenant_id);
create trigger idempotency_logs_set_updated_at before update on public.idempotency_logs
  for each row execute function public.set_updated_at();

-- ── audit_logs ──────────────────────────────────────────────────────────
-- §4.6: the only forensic record. Append-only, never pruned. bigint identity:
-- it is the highest-volume table and its ids are never exposed.
-- actor_id is who called; teafair_agent_id is the accountable staff member,
-- nullable here only for cron/webhook/platform rows (§6.10).
create table public.audit_logs (
  id                bigint generated always as identity primary key,
  tenant_id         uuid references public.tenants (id) on delete restrict,
  actor_id          uuid references public.profiles (id) on delete restrict,
  actor_role        text,
  teafair_agent_id  uuid references public.profiles (id) on delete restrict,
  operation         text not null,
  entity_type       text not null,
  entity_id         text,
  before            jsonb,
  after             jsonb,
  idempotency_key   uuid,
  source            public.audit_source_enum not null,
  created_at        timestamptz not null default now()
);
alter table public.audit_logs enable row level security;
create index idx_audit_logs_tenant_time on public.audit_logs (tenant_id, created_at desc);
create index idx_audit_logs_entity on public.audit_logs (tenant_id, entity_type, entity_id);
create index idx_audit_logs_idempotency on public.audit_logs (idempotency_key)
  where idempotency_key is not null;
create index idx_audit_logs_actor on public.audit_logs (actor_id);
create index idx_audit_logs_teafair_agent on public.audit_logs (teafair_agent_id);

revoke update, delete, truncate on public.audit_logs from public, anon, authenticated, service_role;
create trigger audit_logs_no_update_delete
  before update or delete on public.audit_logs
  for each row execute function public.forbid_mutation();
create trigger audit_logs_no_truncate
  before truncate on public.audit_logs
  for each statement execute function public.forbid_mutation();

-- ── notifications ───────────────────────────────────────────────────────
create table public.notifications (
  id          uuid primary key default gen_random_uuid(),
  tenant_id   uuid references public.tenants (id) on delete restrict,
  user_id     uuid not null references public.profiles (id) on delete restrict,
  kind        text not null,
  title       text not null,
  body        text,
  payload     jsonb not null default '{}'::jsonb,
  read_at     timestamptz,
  created_at  timestamptz not null default now()
);
alter table public.notifications enable row level security;
create index idx_notifications_user on public.notifications (user_id, created_at desc);
create index idx_notifications_unread on public.notifications (user_id) where read_at is null;
create index idx_notifications_tenant on public.notifications (tenant_id);
